language: python

# cache artifacts for faster builds
cache: pip

# build matrix
python:
  - "3.5"
  - "3.6"
  - "3.7"

# build matrix
env:
  - MONGODB=2.6.12
  - MONGODB=3.0.15
  - MONGODB=3.2.22
  - MONGODB=3.4.23
  - MONGODB=3.6.14
  - MONGODB=4.0.12

# safelist
branches:
  only:
  - master

before_install:
  - sudo apt-get install gcc

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &

before_script:
  - pip install -U numpy pandas pymongo

script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install -U sphinx && python setup.py doc --test; fi
